language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "3.9"
  - "3.9-dev"
  - "nightly"

addons:
  chrome: stable
  apt:
    packages:
      chromium-chromedriver

# Note: no need to specify virtualenv, see:
# https://docs.travis-ci.com/user/languages/python/#travis-ci-uses-isolated-virtualenvs
install:
  - pip install -r requirements.txt

# lint

# pages

# tests 
# straight unittest
script:
    - python -m unittest demodocusfw/tests/test_dom_manipulations.py
    - python -m unittest demodocusfw/tests/test_template.py
    - python -m unittest demodocusfw/tests/test_compare.py
    - python -m unittest demodocusfw/tests/test_reachable.py
    - python -m unittest demodocusfw/tests/test_selenium_integration.py
    - python -m unittest demodocusfw/tests/test_web_access_chrome.py
    - python -m unittest demodocusfw/tests/test_event_tracking.py
    - python -m unittest demodocusfw/tests/test_animation.py
    - DEM_RUN_EXTENDED=False python -m unittest demodocusfw/tests/test_crawler.py
    - python -m unittest demodocusfw/tests/test_keyboard_crawl.py
    - DEM_RUN_EXTENDED=False python -m unittest demodocusfw/tests/test_crawl_graph.py
    - python -m unittest demodocusfw/tests/test_reduced_crawl.py
    - DEM_RUN_EXTENDED=False python -m unittest demodocusfw/tests/test_analysis.py
    - python -m unittest demodocusfw/tests/test_keyboard_eval.py
